services:
  postgre:
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=kubenews
      - POSTGRES_DB=kubenews
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data

volumes:
  postgre_docker_vol:
    name: postgre_exemplo_vol