name: Exemplo Artifact
run-name: Exemplo workflow para Artifact, executado por ${{ github.actor}}
on:
  workflow_dispatch:  
env:
  nome-artefato: teste-artefato
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Listagem de Arquivos
        run: ls -R
      - name: Gerar alguns arquivos
        run: |
          mkdir -p artefatos
          echo "Arquivo de teste 1" > ./artefatos/primeiro_arquivo.txt
          echo "Arquivo de teste 2" > ./artefatos/segundo_arquivo.txt
          echo "Arquivo de teste 3" > ./artefatos/terceiro_arquivo.txt
          echo "Arquivo de teste 4" > ./artefatos/quarto_arquivo.txt
      - name: Envio dos Arquivos
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name: $ {{ env.nome-artefato }}
          path: ./artefatos
      - name: Listagem de Arquivos
        run: ls -R
      - name: Endereço para Obter os artefatos
        run: |
          echo "Endereço para obter os artefatos:"
          echo "${{ steps.upload-artifact.outputs.artifact_url }}"
  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Listagem de Arquivos
        run: ls -R
      - name: Download do Artefato
        uses: actions/download-artifact@v4
        with:
          name: t$ {{ env.nome-artefato }}
      - name: Listagem de Arquivos
        run: ls -R