name: Exemplo Input
run-name: Exemplo workflow para input, executado por ${{ github.actor}}
on:
  workflow_dispatch:
    inputs:
      versao:
        type: string
        required: true
        default: "dev"
        description: 'Versão da nova release'
      numero_card:
        type: number
        required: true
        description: 'Número do card da tarefa desse commit'
      fazer_deploy:
        type: boolean
        required: true
        description: 'Deseja fazer deploy?'
      ambiente:
        type: choice
        required: true
        description: 'Ambiente para deploy'
        options:
          - Desenvolvimento
          - Homologação
          - Produção
jobs:
  valores_input:
    runs-on: ubuntu-latest
    steps:
      - name: Exibindo o contexto de input completo
        run: echo "${{ toJson(inputs)}}"
      - name: Exibindo os valores individualmente
        run: |
          echo "Esses são os valores passado nos inputs"
          echo "Versão: ${{ inputs.versao }}"
          echo "Número do card: ${{ inputs.numero_card }}"
          echo "Fazer deploy: ${{ inputs.fazer_deploy }}"
          echo "Ambiente: ${{ inputs.ambiente }}"
      
# Exemplo de execução      
#      - name: Exibindo o contexto de input completo
#        run: |
#          echo "Versão: ${{ github.event.inputs.versao }}"
#          echo "Número do card: ${{ github.event.inputs.numero_card }}"
#          echo "Fazer deploy: ${{ github.event.inputs.fazer_deploy }}"
#          echo "Ambiente: ${{ github.event.inputs.ambiente }}"