name: Exemplo Output
run-name: Exemplo workflow para output, executado por ${{ github.actor}}
on:
  workflow_dispatch:   
jobs:
  gerando_output:
    runs-on: ubuntu-latest
#    outputs:
#      output-shell: ${{ steps.gerando-output.outputs.action_random }}
#      output-gerador-senha: ${{ steps.gerador-senha.outputs.password }}
    steps:
      - name: Gerando output com shell
        id: gerando-output
        run: |
          ACTION_RANDOM=$(( $RANDOM ))
          echo action_random=$ACTION_RANDOM >> $GITHUB_OUTPUT

      - name: Exibindo o outpu da action exemplo output
        run: echo "${{ steps.exemplo-output.action_random}}"

      - name: Gerador de Senha
        id: gerador-senha
        uses: aammirmirza/RandomPasswordGenerator@v1.1
        with:
          length: 15
          special: true
          upper: true
          lower: true
          number: true

      - name: Exibindo a senha gerada
        run: echo "${{ steps.gerador-senha.outputs.password }}"