FROM cgr.dev/chainguard/node:latest

WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

# Install dependencies as root user
USER root
RUN npm install

# Copy the rest of the application code
COPY . .

# Ensure permissions are correct for all files
RUN chown -R node:node /app

# Switch to a non-root user
USER node

# Expose the port your application will run on
EXPOSE 8080

# Run the application
ENTRYPOINT [ "node", "server.js" ]
